# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: |
    Write-Host "Initial Path"
    echo $env:Path
    Write-Host "New Path"
    # Clean up path (remove MWING, Git, ... ), recommanded for craft
    $env:Path = "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\"
    $Currentlocation=Get-Location
    Write-Host "Installing Craft"
    .\install_craft.ps1
    Write-Host "Restore PWD"
    cd -Path $Currentlocation
    Write-Host "Activating craft"
    C:\CraftRoot\craft\craftenv.ps1
    Write-Host "Add Craft blueprint repository"
    craft --add-blueprint-repository https://github.com/samdolt/craft-blueprints-glabels-qt.git
    Write-Host "Build glabels-qt"
    craft glabels-qt
    craft --compile glabels-qt
    craft nsis
    craft --package glabels-qt
  displayName: 'Build'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'C:\CraftRoot\tmp'
  displayName: 'Publish'
