# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: |
    Write-Host "Initial Path"
    echo $env:Path
    Write-Host "New Path"
    # Clean up path (remove MWING, Git, ..
    $env:Path = "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Micr"
    $Currentlocation=Get-Location
    Write-Host "Installing Craft"
    .\install_craft.ps1
    Write-Host "Add glabels to Craft"
    mkdir "C:\CraftRoot\etc\blueprints\locations\craft-blueprints-kde\qt-apps\glabels-qt"
    Write-Host "Restore PWD"
    cd -Path $Currentlocation
    Copy-Item "glabels-qt.py" -Destination "C:\CraftRoot\etc\blueprints\locations\craft-blueprints-kde\qt-apps\glabels-qt"
    Write-Host "Activating craft"
    C:\CraftRoot\craft\craftenv.ps1
    Write-Host "Build glabels-qt"
    craft glabels-qt
    craft --compile glabels-qt
    craft nsis
    craft --package glabels-qt
    
  displayName: 'Build'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'C:\CraftRoot\tmp' 
